[package]
name = "block-header-proof-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.release]
lto = true
opt-level = "z"

[dependencies]
risc0-zkvm-guest = "0.11"

[build-dependencies]
risc0-build = "0.11"