[package]
name = "block-header-zkproof-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.release]
lto = true
opt-level = "z"

[dependencies]
risc0-zkvm-guest = "0.11"
block-header-zkproof-core = { path = "../../core"}


[build-dependencies]
risc0-build = "0.11"