[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.11", features = ["cargo"] }
block-header-core = { path = "../core" }
block-header-validity-methods = { path = "../methods" }
risc0-zkvm = "0.11.0-rc.4"
bincode = "1.3"
hex = "0.4"
serde_json = "1.0"